# Copyright (C) 2019 Kuy Mainwaring (https://github.com/kuym)

# select the cross-compiler from the SDK
CC?=gcc
AR?=ar

build_dir=out
obj_dir=$(build_dir)/obj

# cflags to apply to all targets in this makefile
#   (making these specific per-binary-output or per-source-file is possible but difficult)
global_cflags=-O3 -Wall


# if we `make all` or simply `make`, build these things
# todo in future: add cookd probed
all: tests selfupdate

# define virtual targets
.PHONY: all mkdirs tests inflate-tests deflate-tests corpus corpus-canterbury \
	selfupdate clean


#  General:

# build *.o files in $(obj_dir) from the corresponding *.c
$(obj_dir)/%.o: %.c
	@mkdir -p $(shell dirname $@)
	$(CC) $(global_cflags) -c $< -o $@

# build *.oo files in $(obj_dir) from the corresponding *.cpp
$(obj_dir)/%.oo: %.cpp
	@mkdir -p $(shell dirname $@)
	$(CC) $(global_cflags) -c $< -o $@

# make output directories if they don't already exist
mkdirs:
	@mkdir -vp $(build_dir)
	@mkdir -vp $(obj_dir)


#  Tests:

# If a test recipe fails part-way through, drop its log so the next `make` runs
# it again instead of treating the partial log as up to date.
.DELETE_ON_ERROR:

$(build_dir)/inflate-test: test-common.c inflate-test.c inflate.c inflate.h
	@mkdir -p $(build_dir)
	$(CC) $(global_cflags) -o $@ \
		test-common.c \
		inflate-test.c \
		inflate.c

$(build_dir)/deflate-test: test-common.c deflate-test.c deflate.c deflate.h crc32.c crc32.h
	@mkdir -p $(build_dir)
	$(CC) $(global_cflags) -o $@ \
		test-common.c \
		deflate-test.c \
		deflate.c \
		crc32.c

$(build_dir)/inflate-test.log: $(build_dir)/inflate-test test/inflate1.gz test/inflate1.out
	$(build_dir)/inflate-test test/inflate1.gz $(build_dir)/inflate1.out > $(build_dir)/inflate-test.log
	diff $(build_dir)/inflate1.out test/inflate1.out > $(build_dir)/inflate-diff.log


#  Compression test corpus:
#
# The samples are regenerated by test/make-corpus.sh, which mixes /dev/urandom
# (incompressible; exercises stored blocks) with degenerate, highly repetitive
# and block-boundary-straddling inputs.  `make corpus-canterbury` additionally
# drops in the Canterbury Corpus, the sample set conventionally used to
# regression-test gzip and friends.

corpus_dir=$(build_dir)/corpus
corpus_stamp=$(corpus_dir)/.stamp
canterbury_url=https://corpus.canterbury.ac.nz/resources/cantrbry.tar.gz

$(corpus_stamp): test/make-corpus.sh
	@mkdir -p $(corpus_dir)
	@sh test/make-corpus.sh $(corpus_dir)
	@touch $(corpus_stamp)

corpus: $(corpus_stamp)

# Optional, and requires network access.  Adds ~2.8MB of real-world samples.
corpus-canterbury: $(corpus_stamp)
	@echo "Fetching the Canterbury Corpus into $(corpus_dir)..."
	@curl -fsSL $(canterbury_url) | tar -xzf - -C $(corpus_dir)
	@rm -f $(build_dir)/deflate-test.log
	@echo "Added.  Re-run 'make deflate-tests' to cover it."


# Compress every sample, then require that both this toolkit's own inflate-test
# and a stock gzip recover the original byte for byte.
$(build_dir)/deflate-test.log: $(build_dir)/deflate-test $(build_dir)/inflate-test $(corpus_stamp)
	@rm -f $@
	@pass=0; fail=0; inTotal=0; outTotal=0; \
	for f in $(corpus_dir)/*; do \
		name=`basename $$f`; \
		echo "--- $$name" >> $@; \
		if ! $(build_dir)/deflate-test $$f $(build_dir)/corpus.gz >> $@ 2>&1; then \
			echo "FAIL (compress): $$name"; fail=`expr $$fail + 1`; continue; \
		fi; \
		if ! $(build_dir)/inflate-test $(build_dir)/corpus.gz $(build_dir)/corpus.out >> $@ 2>&1; then \
			echo "FAIL (inflate-test returned an error): $$name"; fail=`expr $$fail + 1`; continue; \
		fi; \
		if ! cmp -s $$f $(build_dir)/corpus.out; then \
			echo "FAIL (inflate-test round-trip mismatch): $$name"; fail=`expr $$fail + 1`; continue; \
		fi; \
		if ! gunzip -c $(build_dir)/corpus.gz > $(build_dir)/corpus.ungz 2>/dev/null; then \
			echo "FAIL (stock gzip rejected the stream): $$name"; fail=`expr $$fail + 1`; continue; \
		fi; \
		if ! cmp -s $(build_dir)/corpus.ungz $$f; then \
			echo "FAIL (stock gzip round-trip mismatch): $$name"; fail=`expr $$fail + 1`; continue; \
		fi; \
		inSize=`wc -c < $$f`; outSize=`wc -c < $(build_dir)/corpus.gz`; \
		inTotal=`expr $$inTotal + $$inSize`; outTotal=`expr $$outTotal + $$outSize`; \
		printf "  ok  %-28s %9s -> %9s\n" "$$name" "$$inSize" "$$outSize"; \
		pass=`expr $$pass + 1`; \
	done; \
	echo "deflate: $$pass passed, $$fail failed ($$inTotal bytes in, $$outTotal bytes out)" | tee -a $@; \
	test $$fail -eq 0

inflate-tests: $(build_dir)/inflate-test.log

deflate-tests: $(build_dir)/deflate-test.log

tests: inflate-tests deflate-tests


#  Selfupdate

selfupdate_output=$(build_dir)/selfupdate.a

selfupdate_sources=\
	inflate.c \
	deflate.c \
	crc32.c \
	sha256.c \
	aes128.c

# transform   foo.c => $(obj_dir)/foo.o   and   foo.cpp => $(obj_dir)/foo.oo
selfupdate_objects=$(patsubst %,$(obj_dir)/%,$(patsubst %.c,%.o,$(patsubst %.cpp,%.oo,$(selfupdate_sources))))

# to make selfupdate, create directories and build the selfupdate executable
selfupdate: mkdirs tests $(selfupdate_output)

# build selfupdate from its sources
$(selfupdate_output): $(selfupdate_objects)
	$(AR) -r $(selfupdate_output) $(selfupdate_objects)


# generate selfupdate dependencies
selfupdate_depend: $(obj_dir)/.selfupdate_depend

# use gcc's -MM option to generate gnu make dependencies. For each source, generate the expected
#   object file name (this is part of the target definition but contains no commands) and append it
#   to the dependencies sub-makefile.  This sub-makefile is included into this one and defines
#   dependencies for sources
$(obj_dir)/.selfupdate_depend: $(selfupdate_sources)
	@mkdir -vp $(obj_dir)
	@rm -f $(obj_dir)/.selfupdate_depend
	@for f in $^; do \
		$(CC) $(global_cflags) -MM -MT $(obj_dir)/$$(echo $$f | sed -E "s/\.cpp$$/.oo/" | sed -E "s/\.c$$/.o/") $$f >> $(obj_dir)/.selfupdate_depend ; \
	done

# include dependencies for selfupdate
-include $(obj_dir)/.selfupdate_depend

clean:
	rm -f	$(build_dir)/inflate-test $(build_dir)/deflate-test \
			$(build_dir)/selfupdate-test \
			$(build_dir)/inflate-test.log $(build_dir)/inflate-diff.log \
			$(build_dir)/deflate-test.log $(build_dir)/selfupdate-test.log \
			$(build_dir)/inflate1.out $(build_dir)/corpus.gz $(build_dir)/corpus.out \
			$(build_dir)/corpus.ungz \
			$(selfupdate_output) $(obj_dir)/.selfupdate_depend $(selfupdate_objects)
	rm -rf	$(corpus_dir)
